---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: openops
  labels:
    app: openops-analytics
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8088
    protocol: TCP
    name: tcp-analytics
  selector:
    app: openops-analytics
