---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openops.fullname" . }}-tables-configmap
  labels:
    {{- include "openops.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.openops.tables.environment }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openops.fullname" . }}-tables
  labels:
    app: {{ include "openops.fullname" . }}-tables
    {{- include "openops.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.openops.tables.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: "50%"
  selector:
    matchLabels:
      app: {{ include "openops.fullname" . }}-tables
      {{- include "openops.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "openops.fullname" . }}-tables
        {{- include "openops.labels" . | nindent 8 }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: {{ include "openops.fullname" . }}-tables
      serviceAccountName: {{ include "openops.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.openops.serviceAccount.automount }}
      {{- with .Values.openops.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init
        image: "{{ .Values.openops.initContainer.image }}:{{ .Values.openops.initContainer.tag }}"
        imagePullPolicy: {{ .Values.openops.initContainer.imagePullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - echo "Checking if PostgreSQL and Redis is ready..";
          until ((nc -zv $DATABASE_HOST $DATABASE_PORT && nc -zv $REDIS_URL $REDIS_PORT));
          do 
            echo "Waiting for PostgreSQL and Redis to respond..";
            sleep 2s;
          done;
          echo "PostgreSQL and Redis responded. Exiting!";
        envFrom:
        - configMapRef:
            name: {{ include "openops.fullname" . }}-global-configmap
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
      containers:
      - name: {{ include "openops.fullname" . }}-tables
        image: "{{ .Values.openops.tables.image }}:{{ .Values.openops.tables.tag }}"
        imagePullPolicy: {{ .Values.openops.tables.imagePullPolicy }}
        ports:
        - name: tcp-tables
          containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "openops.fullname" . }}-tables-configmap
        - configMapRef:
            name: {{ include "openops.fullname" . }}-global-configmap
        env:
        - name: BASEROW_PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "openops.fullname" . }}-global-configmap
              key: FRONTEND_URL
        - name: BASEROW_PRIVATE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "openops.fullname" . }}-global-configmap
              key: TABLES_BACKEND_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: encryption-creds
              key: encryption_key
        - name: BASEROW_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: encryption-creds
              key: jwt_secret
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: database_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: database_password
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: redis_url
        resources:
          {{- toYaml .Values.openops.tables.resources | nindent 10 }}
        readinessProbe:
          tcpSocket:
            port: 80
          {{- toYaml  .Values.openops.readinessProbe | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 80
          {{- toYaml  .Values.openops.livenessProbe | nindent 10 }}
        {{- if .Values.openops.tables.persistence.existingClaim }}
        volumeMounts:
        - name: tables-data
          mountPath: {{ .Values.openops.tables.persistence.mountPath }}
        {{- end }}
      {{- if .Values.openops.tables.persistence.existingClaim }}
      volumes:
      - name: tables-data
        persistentVolumeClaim:
          claimName: {{ .Values.openops.tables.persistence.existingClaim }}
      {{- end }}
      {{- with .Values.openops.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openops.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openops.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- if not .Values.openops.ingress.controller.istio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openops.fullname" . }}-tables
  labels:
    app: {{ include "openops.fullname" . }}-tables
    {{- include "openops.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: tcp-tables
  selector:
    app: {{ include "openops.fullname" . }}-tables
{{- end }}
