---
apiVersion: v1
kind: Secret
metadata:
  name: database-creds
data:
  database_user: {{ .Values.openops.storage.postgres.username | b64enc | quote }}
  database_password: {{ .Values.openops.storage.postgres.password | b64enc | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-creds
data:
  jwt_secret: {{ .Values.openops.secrets.jwt_secret | default (include "randomHex" .) | b64enc | quote }}
  encryption_key: {{ .Values.openops.secrets.encryption_key | default (include "randomHex" .) | b64enc | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: openops-creds
data:
  admin_username: {{ .Values.openops.secrets.admin_username | b64enc | quote }}
  admin_password: {{ .Values.openops.secrets.admin_password | b64enc | quote }}
  superuser_password: {{ .Values.openops.secrets.superuser_password | b64enc | quote }}
type: Opaque
---
{{- $redisConf := include "redisConf" . | fromJson }}
{{- $host := $redisConf.REDIS_URL }}
{{- $port := print $redisConf.REDIS_PORT }}
{{- $database := print $redisConf.REDIS_DB }}
{{- $username := "default" }}
{{- $password := .Values.openops.session.redis.password | default (randAlphaNum 16) | toString }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-creds
data:
  redis_username: {{ $username | b64enc | quote }}
  redis_password: {{ $password | b64enc | quote }}
  redis_url: {{ printf "redis://%s:%s@%s:%s/%s" $username $password $host $port $database | b64enc | quote }}
type: Opaque
