---
{{- if .Values.openops.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openops.serviceAccountName" . }}
  labels:
    {{- include "openops.labels" . | nindent 4 }}
  {{- with .Values.openops.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.openops.serviceAccount.automount }}
{{- end }}
