apiVersion: v2
name: openops
description: No-Code FinOps automation platform

dependencies:
- name: postgresql
  version: ~16.5.6
  repository: https://charts.bitnami.com/bitnami
  condition: openops.storage.postgres.deploy
- name: redis
  version: ~20.11.4
  repository: https://charts.bitnami.com/bitnami
  condition: openops.session.redis.deploy

type: application

version: 0.0.1
appVersion: "0.0.1"
