---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-db
  namespace: openops
data:
  init-db.sh: |-
    #!/bin/bash
    set -e

    echo "[START] creating database for analytics and tables..."

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
      CREATE DATABASE tables;
      CREATE DATABASE analytics;
    EOSQL

    echo "[COMPLETE] creating database for analytics and tables ..."
