---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: openops
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: tcp-postgres
  selector:
    app: postgres
