---
apiVersion: v1
kind: Service
metadata:
  name: engine
  namespace: openops
  labels:
    app: openops-engine
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3005
    protocol: TCP
    name: tcp-engine
  selector:
    app: openops-engine
