---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: openops
  labels:
    app: openops-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: tcp-app
  selector:
    app: openops-app
