---
apiVersion: v1
kind: Service
metadata:
  name: tables
  namespace: openops
  labels:
    app: openops-tables
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: tcp-table
  selector:
    app: openops-tables
