---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: openops
  labels:
    app: openops-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: tcp-redis
  selector:
    app: openops-redis
